spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  jpa:
    show-sql: false
    hibernate.ddl-auto: create


msh:
  socialauth:
    base-callback-url: "https://million-steps-home.herokuapp.com"

  payment:
    environment: sandbox
    merchant-id: f7t47vbjtzjzcgrt
    public-key: w8842xsbz7jc4yv4
    private-key: 6ab898af63214477e8d381e10804a7ac