server:
  port: 8080

spring:
  application:
    name: Million Steps Home
  datasource:
    username: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true
      path: /h2

msh:
  socialauth:
    base-callback-url: "http://localhost:8080"
    success-page-url: ""
    access-denied-page-url: "/access-denied"