server:
  port: 8080

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: WARN
      hibernate: INFO

spring:
  application:
    name: Million Steps Home
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/msh
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect


msh:
  socialauth:
    base-callback-url: "http://localhost:8080"
    success-page-url: ""
    access-denied-page-url: ""

  payment:
    environment: sandbox
    merchant-id: f7t47vbjtzjzcgrt
    public-key: w8842xsbz7jc4yv4
    private-key: 6ab898af63214477e8d381e10804a7ac