server:
  port: 8080

spring:
  application:
    name: Million Steps Home
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/msh

  jpa:
    show-sql: true
    hibernate.ddl-auto: create
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  #h2:
   # console:
   #   enabled: true
   #   path: /h2

msh:
  socialauth:
    base-callback-url: "http://localhost:8080"
    success-page-url: ""
    access-denied-page-url: ""

    payment:
      BT_ENVIRONMENT: sandbox
      BT_MERCHANT_ID: YOUR_MERCHANT_ID
      BT_PUBLIC_KEY: YOUR_PUBLIC_KEY
      BT_PRIVATE_KEY: YOUR_PRIVATE_KEY